<a href="https://colab.research.google.com/github/Tiberu2611/BaiTapPython/blob/main/Baitaptailop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import pandas as pd
import statistics as sta

Cho v là 1 vector hàng

In [16]:
V = np.array([1, 3, 5])
print(V)

[1 3 5]


Cho w là 1 vector cột

In [15]:
W = np.array([[4], [6], [8]])
print(W)

[[4]
 [6]
 [8]]


Hãy xác định số chiều (ndim), kích thước
(shape) của 2 vector v và w; In 2 vector v và
w ra màn hình

In [23]:
print(V)
print("số chiều của V:", V.ndim)
print("kích thước của V:", V.shape)
print(W)
print("số chiều của W:", W.ndim)
print("kích thước của W:", W.shape)


[1 3 5]
số chiều của V: 1
kích thước của V: (3,)
[[4]
 [6]
 [8]]
số chiều của W: 2
kích thước của W: (3, 1)


Cho u và w là 2 vector cột có kích
thước (m, 1). Hãy tạo ma trận X bằng
cách ghép 2 vector cột u và w lại với
nhau

In [26]:
U = np.array([[3], [6], [9]])
np.column_stack((U, W))

array([[3, 4],
       [6, 6],
       [9, 8]])

Hãy tạo ma trận X có giá trị như sau

-Hãy tạo ma trận X bằng np.array()

In [35]:
X = np.array([1, 2, 3, 4, 7, 9])
print(X)

[1 2 3 4 7 9]


-Hãy tạo ma trận X bằng hàm np.reshape()

In [38]:
X = np.reshape(X, (2, 3))
print(X)

[[1 2 3]
 [4 7 9]]


In [40]:
print("số chiều của X:", X.ndim)
print("kích thước của X:", X.shape)
print(X)

số chiều của X: 2
kích thước của X: (2, 3)
[[1 2 3]
 [4 7 9]]


Hãy nhân ma trận X với vector v

In [41]:
print("giá trị nhân ma trận X với vector V",np.dot(X, V))

giá trị nhân ma trận X với vector V [22 70]


Hãy nhân ma trận X với vector w

In [42]:
print("giá trị nhân ma trận X với vector W",np.dot(X, W))

giá trị nhân ma trận X với vector W [[ 40]
 [130]]


Xét ma trận X ở câu 5, hãy tìm ma trận
chuyển vị của X, ký hiệu là

In [43]:
print(X.T)

[[1 4]
 [2 7]
 [3 9]]
